[package]
name = "senor_borroso"
version = "0.1.0"
authors = ["logan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidecode = "0.3.0"
fxhash = "0.2.1"
levenshtein = "1.0.5"
hnsw = "0.7.0"
space = "0.11.0"